language: python
dist: trusty
python:
  - "2.7"
services:
  - postrgresql
before_install:
  - sudo ./apt/production.sh
  - sudo ./apt/testing.sh
install:
  - "pip install setuptools==32"
  - "pip install -r requirements.txt"
  - "pip install -r requirements/testing.txt"
before_script:
  - "psql -c 'CREATE DATABASE manchester_traffic_offences;' -U postgres"
  - "python manage.py syncdb --noinput"
  - "python manage.py compilemessages"
env:
  - POSTGRES_USER=postgres DJANGO_SETTINGS_MODULE=make_a_plea.settings.testing
script:
  - "python manage.py test"
