language: python
dist: trusty
addons:
  chrome: stable
python:
  - "3.6"
notifications:
  email: false
services:
  - postgresql
  - rabbitmq
before_install:
  - sudo apt-get -qq update
  - sudo ./apt/production.sh
  - sudo ./apt/testing.sh
  - wget -N https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo mv ~/chromedriver /usr/local/bin/chromedriver
install:
  - "pip install setuptools==32"
  - "pip install -r requirements/testing.txt"
before_script:
  - "psql -c 'CREATE DATABASE manchester_traffic_offences;' -U postgres"
  - "python manage.py migrate --noinput"
  - "python manage.py compilemessages"
env:
  - POSTGRES_USER=postgres DJANGO_SETTINGS_MODULE=make_a_plea.settings.testing
script:
  - coverage run --source='.' manage.py test
  - coverage report
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then codeclimate-test-reporter; fi
  - python manage.py test --settings=api.settings.testing -p "api_test_*.py"
  - python manage.py loaddata features/fixtures.yaml
  - python manage.py runserver &
  - mailmock -p 1025 -o /tmp/mailmock -n &
  - celery worker -A make_a_plea -D
  - sleep 2
  - behave --format progress3 -Dheadless
