# Note that this config duplicates the base urls in makeaplea-deploy
# Note also that required fixtures will not be installed on prod so it will
# never be possible to run these tests on prod.
---
local:
    :url: http://127.0.0.1:8000/
dev:
    :url: https://dev.makeaplea.dsd.io/
staging:
    :url: https://makeaplea.dsd.io/


