# local dev env

django:
  build: .
  ports:
    - "8111:8111"
    - "8000:8000"
  links:
    - postgres:db
  # local dev env variables which are kept out of version control
  environment:
    - POSTGRES_HOST=db
    - POSTGRES_USER=makeaplea
    - POSTGRES_PASS=password
    - POSTGRES_PORT=5432
    - POSTGRES_DB=makeaplea
    - DJANGO_SETTINGS_MODULE=make_a_plea.settings.local
  command: ./manage.py runserver 0.0.0.0:8000 
  volumes:
    - .:/makeaplea
postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=makeaplea
    - POSTGRES_PASSWORD=password
