# local dev env

django:
  build: .
  ports:
    - "8000:8000"
  links:
    - postgres:db
  env_file: docker/django-env
postgres:
  image: postgres:9.4
  environment:
    - POSTGRES_USER=makeaplea
    - POSTGRES_PASSWORD=password