FROM python:2.7

ENV DJANGO_SETTINGS_MODULE=make_a_plea.settings.docker
WORKDIR /makeaplea

# Install system dependencies
COPY apt/ ./apt
RUN apt-get -y update \
  && ./apt/production.sh \
  && ./apt/testing.sh \
  && rm -rf /var/lib/apt/lists/*

# Install phantomjs
RUN mkdir /tmp/phantomjs \
  && curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
      | tar -xj --strip-components=1 -C /tmp/phantomjs \
  && mv /tmp/phantomjs/bin/phantomjs /usr/local/bin

# Install python dependencies
COPY requirements/ ./requirements
RUN pip install --no-cache-dir -r requirements/testing.txt

COPY . .

CMD ["./test_unit.sh"]
