FROM python:2.7

ENV HOME=/app

ADD . $HOME
WORKDIR $HOME

RUN apt-get -y update && apt/development.sh

# todo cleanup requirements
RUN pip install -r requirements/dev.txt && pip install -r requirements/testing.txt

COPY make_a_plea/settings/local.py.example make_a_plea/settings/local.py

RUN echo "local  all all trust" > /etc/postgresql/9.4/main/pg_hba.conf \
&& service postgresql start \
&& psql -c 'CREATE DATABASE manchester_traffic_offences;' -U postgres \
&& python manage.py migrate --noinput \
&& python manage.py loaddata features/fixtures.yaml

RUN python manage.py compilemessages

CMD ["./run_dev.sh"]

EXPOSE 80
