version: "3.1"
services:
  makeaplea:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DJANGO_SETTINGS_MODULE: "make_a_plea.settings.dev"
      DB_HOST:     "postgres"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:
    command: ./run_compose.sh
    links:
      - postgres
    volumes:
      - .:/makeaplea

  makeaplea_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DJANGO_SETTINGS_MODULE: "api.settings.dev"
      DB_HOST:     "postgres"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:
    command: ./run_compose.sh
    links:
      - postgres
    volumes:
      - .:/makeaplea

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DJANGO_SETTINGS_MODULE: "make_a_plea.settings.testing"
      DB_HOST:     "postgres"
      DB_USERNAME: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB:
    command: ./test_unit.sh
    links:
      - postgres
    volumes:
      - .:/makeaplea

  test-cucumber:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - makeaplea
