# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0039_auto_20180522_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtemailcount',
            name='total_guilty_court',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='courtemailcount',
            name='total_guilty_no_court',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='online_guilty_attend_court_pleas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usagestats',
            name='online_guilty_no_court_pleas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
