# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0040_auto_20180523_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(null=True)),
                ('authentication', models.BooleanField(default=False)),
                ('details', models.BooleanField(default=False)),
                ('plea', models.BooleanField(default=False)),
                ('company_finances', models.BooleanField(default=False)),
                ('income_base', models.BooleanField(default=False)),
                ('your_status', models.BooleanField(default=False)),
                ('your_self_employment', models.BooleanField(default=False)),
                ('your_out_of_work_benefits', models.BooleanField(default=False)),
                ('about_your_income', models.BooleanField(default=False)),
                ('your_benefits', models.BooleanField(default=False)),
                ('your_pension_credits', models.BooleanField(default=False)),
                ('your_income', models.BooleanField(default=False)),
                ('hardship', models.BooleanField(default=False)),
                ('household_expenses', models.BooleanField(default=False)),
                ('other_expenses', models.BooleanField(default=False)),
                ('review', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plea.Case')),
            ],
        ),
    ]
