# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0041_stagecompletiontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecompletiontable',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
