# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0041_casetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagestats',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plea.Court'),
        ),
    ]
