# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0042_auto_20180621_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecompletiontable',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plea.Case'),
        ),
    ]
