# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plea', '0043_auto_20180621_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagecompletiontable',
            old_name='case_id',
            new_name='case',
        ),
    ]
