version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build:
    parameters:
      env_name:
        type: string
      ecr_endpoint:
        type: string

    docker:
      - image: 'circleci/python:3.6'
        environment:
          DJANGO_SETTINGS_MODULE: make_a_plea.settings.testing
          POSTGRES_DB: manchester_traffic_offences
          POSTGRES_USER: postgres
          POSTGRES_PASS: password
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost

      - image: 'circleci/postgres:10.4'
        environment:
          POSTGRES_DB: manchester_traffic_offences
          POSTGRES_USER: postgres
          POSTGRES_PASS: password
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run:
          name: Install linux dependencies
          command: |
            sudo apt-get -qq update
            sudo ./apt/production.sh
            sudo ./apt/testing.sh
            wget -N https://chromedriver.storage.googleapis.com/114.0.5735.16/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            sudo mv ~/chromedriver /usr/bin/chromedriver
            sudo chown root:root /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver

      - run:
          name: Install python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install setuptools==32
            pip install -r requirements/testing.txt
            pip install behave==1.2.6 behaving==1.5.6 splinter==0.14.0 selenium==3.141.0

      - run:
          name: Database migration
          command: |
            . venv/bin/activate
            python manage.py migrate --noinput
            python manage.py compilemessages

      - run:
          name: Unit and E2E tests
          command: |
            . venv/bin/activate
            coverage run --omit 'venv/*' --source='.' manage.py test
            coverage report
            python manage.py test --settings=api.settings.testing -p "api_test_*.py"
            python manage.py loaddata features/fixtures.yaml
            python manage.py runserver &
            mailmock -p 1025 -o /tmp/mailmock -n &
            celery worker -A make_a_plea -D
            sleep 2
            behave --format progress3 -Dheadless

workflows:
   test-build-deploy:
    jobs:
      ### DEV ###
      - build:
          name: build-containers-dev
          env_name: DEV
          ecr_endpoint: ${ECR_ENDPOINT_DEV}
          filters:
            branches:
              only: /^RST-.*/
