version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  build:
    parameters:
      env_name:
        type: string
      ecr_endpoint:
        type: string

    docker:
      - image: 'circleci/python:3.6'
        environment:
          POSTGRES_USER: postgres
          DJANGO_SETTINGS_MODULE: make_a_plea.settings.testing
      - image: 'circleci/postgres:10.4'
        environment:
          POSTGRES_DB: manchester_traffic_offences
          POSTGRES_USER: postgres

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true

      - run:
          name: Install linux dependencies
          command: |
            sudo apt-get -qq update
            sudo ./apt/production.sh
            sudo ./apt/testing.sh
            wget -N https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            sudo mv ~/chromedriver /usr/local/bin/chromedriver

workflows:
   test-build-deploy:
    jobs:
      ### DEV ###
      - build:
          name: build-containers-dev
          env_name: DEV
          ecr_endpoint: ${ECR_ENDPOINT_DEV}
          filters:
            branches:
              only: /^RST-.*/
