source 'https://rubygems.org'

group :test do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'chromedriver-helper', '~> 1.1'
  gem 'codeclimate-test-reporter', require: nil
  gem 'cucumber', '~> 2.4'
  gem 'poltergeist', '1.15.0'
  gem 'pry'
  gem 'rubocop', '~>0.49.1', require: true
  gem 'selenium-webdriver', '~> 3.4'
  gem 'shoulda-matchers'
  gem 'site_prism', '~> 2.9'
  gem 'timecop'
  gem 'webmock', require: false
end